name: Build and Test
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with the desired Node.js version

      # Add any necessary setup steps here, like installing dependencies, etc.

      - name: Build and Test
        run: |
          # Replace these commands with your actual build and test commands
          npm install
          npm run build
          npm test
